site:
  title: Solutions Delivery Platform
  url: http://localhost
  start_page: overview::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: overview
  - url: .
    start_path: deployment-guides
    branches: HEAD
  - url: .
    branches: HEAD
    start_path: learning-labs
ui: 
  bundle: 
    url: https://github.com/boozallen/sdp-docs-skin/releases/download/1.0/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
